### ISSUE TITLE
Identical Turbines behaving differently (Across Chunk borders?)

### ISSUE THREAD

**Issue by Kaethen** [erogenousbeef/BigReactors#232]
Minecraft 1.6.4, 
Other Mods:
Tekkit Pack 1.2.9e, only change I made was update BigReactors from 0.3.0A to 0.3.4A2.
BigReactors Version: Phenomenon observed in Bigreactors 0.3.0A and 0.3.4A2 Hotfix (I didn't test the intermediate Versions.)

Height, width and depth: 11x11x5

I have build two absolutely identical turbines and therefore expected them to behave exactly identical as well, but one of them never reaches more than 300 RPM, while the other one is at 900, both at the same flow rate (435). The set up is absolutely identical so the problem shouldn't be the steam input. I have checked the turbines block for block and even experimented with creative steam generator but to no avail. The only discernable difference I have discovered, that the left turbine, which is the one behaving strangely, is positioned across a chunk border. Turbines though don't seem to have problems with chunk burders. Could it maybe be the very short rotor shaft (3 blocks) of my set up compared to the great width (11 blocks)?

Am I missing something obvious here?

Also: Holy moley! Supplying a sizeable Reactor with water is quite a challenge, even in creative!

![2014-07-16_15 20 39](https://cloud.githubusercontent.com/assets/6020865/3599720/adecc480-0cf1-11e4-94b2-25fdfcd201a1.png)
![2014-07-16_15 21 41](https://cloud.githubusercontent.com/assets/6020865/3599721/adeea688-0cf1-11e4-95b3-768b12375834.png)
![2014-07-16_15 24 20](https://cloud.githubusercontent.com/assets/6020865/3599723/adef5cf4-0cf1-11e4-9611-0ddfbe9ce988.png)
![2014-07-16_15 25 07](https://cloud.githubusercontent.com/assets/6020865/3599722/adeef4bc-0cf1-11e4-8ccf-0f3420aff5a1.png)
![2014-07-16_15 26 52](https://cloud.githubusercontent.com/assets/6020865/3599724/adf0eeca-0cf1-11e4-8a02-cdf5e94ab7ba.png)

**Comment by chris6273** [comment]
It's nothing to do with chunk borders. The iron which was surrounding the turbines in the first picture was acting as part of the coil. Replace the iron with a different material not conductive inside the turbine or use carpenters blocks.
