### ISSUE TITLE
Useing too much Yellowrite

### ISSUE THREAD

**Issue by NassiC** [erogenousbeef/BigReactors#332]
My reactor is useing allmost all of the yellowrite in its core in an instent. First it is running fine, useing a little here and there in a regular pace. Then BAM it uses ~80% of what it has in its core. Because i have a big reactor, that is about 4 stacks.

So even though it only uses 0.065 mb/t it can use about 1000 yellowrite ingots an hour or more.

The other guy on the server dont seem to have this problem. He have 2 smaller reactors running.

**Comment by Nenluen** [comment]
Hello, I've had a similar issue on a smaller scale using Big Reactors 0.4.0rc11 with the ModSauce 1.0.1.0 pack from ATLauncher on a server.  Twice i've come back to my inactive reactor to find most of its fuel missing. It's a 13(W)x13(d)x3(h) reactor (1st Image) with 9 control rods, and the chunk lines seem to cut right across two-thirds of the rods (2nd image), which would explain leaving me with only 33.3% fuel after filling it completely (3rd image),  I plan to move it to a single chunk to hopefully 'cure' my problem, but for this version of the mod, it seems to be a chunk-loading issue.
I've used this reactor for a total of maybe two minutes (it's water cooled, so very inefficient currently) so there is no way that it could have burned the fuel naturally.
![2015-01-29_18 51 37](https://cloud.githubusercontent.com/assets/10765948/5969328/f173befc-a7e7-11e4-95ca-84d73ae0d920.png)
![2015-01-29_18 51 50](https://cloud.githubusercontent.com/assets/10765948/5969329/f17641f4-a7e7-11e4-8651-eb86932ed87f.png)
![2015-01-29_18 52 10](https://cloud.githubusercontent.com/assets/10765948/5969330/f176ba1c-a7e7-11e4-8e0b-43e5c6cf9645.png)
