### ISSUE TITLE
cyanite reprocessor doesn't drop on mining

### ISSUE THREAD

**Issue by Daenyth** [erogenousbeef/BigReactors#378]
I tried to move my cyanite reprocesser and it didn't give it back when I mined it. On version 0.4.0rc11

**Comment by tobywf** [comment]
I've also hit this issue, with 0.4.0rc10 on Direwolf20 1.7 (Forge is  7.10.85.1230, CoFHCore is 3.0.0B7-35). Any vanilla pick and any Tinker's Construct pick will break the block, but not drop it. A standard Buildcraft wrench and Yeta wrench will rotate the block, but shift-click does nothing. Crescent Hammer works fine. Let me know if you need other info or want a new ticket opening. I can reliably reproduce it in a test world.

**Comment by erogenousbeef** [comment]
That's good information, thanks.
