### ISSUE TITLE
Turbine Rotor Bearing allows you to go through it!

### ISSUE THREAD

**Issue by acters124** [erogenousbeef/BigReactors#403]
I don't know but while I was "testing" and "calculating" I somehow went right through it and been able to hop in and out consistently.
![2014-12-21_17 54 05](https://cloud.githubusercontent.com/assets/6981852/5520351/d77dabaa-893a-11e4-9f52-5c779b22795b.png)

**Comment by SReject** [comment]
Can confirm that this only happens with an assembled turbine.

**Comment by acters124** [comment]
Thanks for the confirmation!
Sadly, it is not needed as the author has acknowledged it as a bug.

**Comment by SReject** [comment]
possibly related to #411

**Comment by acters124** [comment]
That bug is possibly due to how the author made the player interact with the blocks...
I'm guessing he's not checking of the player is in the block space.

**Comment by erogenousbeef** [comment]
Looks like a bounding-box problem.

**Comment by erogenousbeef** [comment]
Fixed by 0194855583acff2dbbe9ed264d59a6a511ae5eec, will be out in 0.4.2A.
