### ISSUE TITLE
Greater Control Rod Specificity in Computer Control API

### ISSUE THREAD

**Issue by natabbotts** [erogenousbeef/BigReactors#406]
I'd like to request some additional methods in the computer control (CC and OC) API: 

setControlRodName, to mirror the available get and allow automated "mapping" of the reactor control rods.

getControlRodCoordinate (relative or absolute, am not sure what would be easier/more beneficial). Currently, there is no way to determine where control rods actually are within the reactor, aside from manually naming them all with coordinates and using the getControlRodName method. For more advanced reactor automation programs it would be beneficial to be able to identify and set control rod values based on positions within the reactors - an example is an arbitrarily tall but wide checkerboard reactor - it is better for fertilisation to insert control rods on the outermost fuel rods first when attempting to reduce power output for fuel efficiency, but there is no way to automate this without knowing the physical position of individual control rods.

**Comment by erogenousbeef** [comment]
Sounds fine to me.
