### ISSUE TITLE
Issue with Big Reactors 1.6.4

### ISSUE THREAD

**Issue by Machiavelli1990** [erogenousbeef/BigReactors#407]
I'm having an issue with big reactors 1.6.4. 
I have no idea on how to fix it, kinda dumb in terms of coding 'n stuff.

Crash report located here: http://pastebin.com/FMVWcLjg

Thanks in advance.

**Comment by erogenousbeef** [comment]
For posterity: This appears to be an ID remapping problem. You had blocks with a given ID (likely from another mod) in your world, which then mapped to BR blocks. When removing/adding mods, make sure to do it like this:

1 - Remove any mods you wish to remove.
2 - Load the world. This will set all blocks from the removed mods to air.
3 - Add any new mods.
