### ISSUE TITLE
Suggestion : New Port?

### ISSUE THREAD

**Issue by wesker1213** [erogenousbeef/BigReactors#409]
Is it possible to have a new bidirectional port (that we can import, or export items into/out of) ? I have 2 reasons for this:

1: With ender io conduits, you can import/export with the same conduit.
2: When using separate ports, I still get waste (cyanite) in the import side, which for the sake of my OCD ... is very annoying :(

**Comment by erogenousbeef** [comment]
I'm not sure I understand this request. Access ports are already bidirectional. You can insert fuel into one slot and remove waste from the other.

**Comment by Frontrider** [comment]
Then the problem is a misunderstanding: the port set to input should not output (its already an "issue"), and the output should not input. Make an option to be bi directional, and you no loger see "reactor outputs to the input" issues.

**Comment by erogenousbeef** [comment]
Ports set to "input" only receive output when the output port is too full. I don't see a logical reason why "output" ports shouldn't accept input. Also, the ports will operate bidirectionally if you only have one type of port on the reactor.

**Comment by wesker1213** [comment]
I have a new reactor running with only 1 port. I have an ender io item conduit set to in/out, and it is not pulling the cyanite out. I get what you are saying when there are two ports, but in the case of having only 1, it still isn't functioning correctly. It defeats the purpose of using conduits if it doesn't work both ways as you are indicating. If I have to use buses to get it to push/pull items in and out, I may as well just use 2 ports. Thoughts?
