### ISSUE TITLE
Turbine Light

### ISSUE THREAD

**Issue by SReject** [erogenousbeef/BigReactors#410]
It'd be nice to have a turbine-block that illuminated the inside of a turbine. I like to see the visuals of the turbine running but with large turbines its hard to get lighting inside of them to really show off the turbine.

For the reactors I don't really see the need as the rods produce light.

**Comment by erogenousbeef** [comment]
The easiest thing to do here is probably just to make the turbine shafts produce light.

**Comment by Frontrider** [comment]
beef, i would suggest adding an alternative glowing shaft (craft the shaft with glowstone). That might be the cleanest.

**Comment by Rokmonkey** [comment]
As an additional reason, monsters spawn inside turbines.  Or at least have in the past.

**Comment by erogenousbeef** [comment]
I believe I disabled monsters spawning inside turbines in one of the 0.4 experimentals. Let me know if that's not the case.

**Comment by erogenousbeef** [comment]
Added by 831a5d050f29874336bb0a4533399e91328f6930, will be out in 0.4.2A.
