### ISSUE TITLE
Collusion issue when placing turbine housing blocks to fast

### ISSUE THREAD

**Issue by SReject** [erogenousbeef/BigReactors#411]
When pillaring or spamming turbine blocks, occasionally the turbine block is placed in the same space the player is standing in resulting in suffocation damage.

BRv 0.4.0A

**Comment by erogenousbeef** [comment]
This is likely a problem with your server or network connection. BR doesn't do anything special in this regard.

**Comment by SReject** [comment]
It happens in both SP and SMP equally. Have experienced it on multiple servers, by itself and within other modbacks

Its not consistent, but usually happens when pillaring, or when filling in a wall of the turbine quickly(walking backwards while holding rclick)

**Comment by Frontrider** [comment]
As, beef said, its possible with normal blocks too, its not a br issue. Its can happen if you pillar with anything.
