### ISSUE TITLE
Link Broke?

### ISSUE THREAD

**Issue by MatinPlayz** [erogenousbeef/BigReactors#412]
The CoFHCore link is broken. It will not load for me and I don't know why?
Please tell me how to fix this or if they have to fix the link.

**Comment by acters124** [comment]
You know googling is outrated.. why not ask someone else to give you the link?!
here it is: http://minecraft.curseforge.com/mc-mods/69162-cofhcore/files/2223033
Just click that download button!

You know what I'll make it easy for you!
the actual download link: http://minecraft.curseforge.com/mc-mods/69162-cofhcore/files/2223033/download

**Comment by acters124** [comment]
All Meanyness aside....
Teamcofh.com is down for a while and so report it to teamcofh, not here.

**Comment by erogenousbeef** [comment]
The link appears to be working again.
