### ISSUE TITLE
fuel going missing ?????????

### ISSUE THREAD

**Issue by harry538** [erogenousbeef/BigReactors#413]
so when i fill my reactor up and go off line i think all is well ..... but when i come back even after a short time there is no fuel in the reactor no waste fuel, nothing. this is only happing with my reactor on my server other players are having no troubles with theres.
anybody got a clue why this could be happing ?

**Comment by Frontrider** [comment]
picture of the setup?

**Comment by acters124** [comment]
This is very strange!
Someone has turbine problems and another has almost the exact same problem with thier reactors!
Actually they seem different but it could be a problem with how the information is being stored when the chunks unload.

Can you reproduce this in a single player world?
Did you have a chunkloader in the area?(that contains your whole reactor)

**Comment by erogenousbeef** [comment]
Which version of Big Reactors, COFHCore and Forge are you running? What other mods are you running? Are you on SSP or SMP? Can you provide a screenshot of your reactor? Does this problem happen consistently (i.e. every time you log off/log on) or did it only happen once?

**Comment by aik88** [comment]
Hi same issue on our server. the reactor size is 5x11x7, 14 fuel rods, cooling with cryotheum. this issue is random, reactors like 7x7x7 works perfect...

Big Reactors 0.4.1A2
CoFH Core 3.0.0B9-80
Forge 10.13.2.1277

Modlist: http://pastebin.com/RZCqM6jM
hope this informations are enough :)

**Comment by Robytfc** [comment]
Hi I am having the same issue on our server. We are running FTB's Direwolf20 1.7.10  v1.0.3

Reactor size: 7x7x7
Fuel rods: 5
Cooling: Resonant Ender

It seems as if the reactor is being reset when loaded/unloaded. I have filled the reactor to 100% full and left some ingots ready for it to take twice now and both times I have come back to a reactor with no waste and only 40% fuel. One time I disconnected from the server and another was when I went out of the chucks my reactor/base is in. 

I find it strange how both times I have come back to 40% fuel so many this hold some value. 

Mods used are https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.0.3

Forge 10.13.2.1272
Big Reactors 0.4.0A

P.S no chunk loaders are present

![2015-01-14_20 30 23](https://cloud.githubusercontent.com/assets/1278265/5747304/ebb3dca0-9c2e-11e4-8528-3721db236936.png)

![2015-01-14_20 30 28](https://cloud.githubusercontent.com/assets/1278265/5747334/194143a6-9c2f-11e4-85d4-41a030a4ae23.png)

**Comment by acters124** [comment]
No has responded with new information... so I ask:
Reproducible in Single player?
Coordinates?
Reproducible with the NEWEST forge?
Can you see if this happens to the Cyanite Reprocessor?

**Comment by erogenousbeef** [comment]
@Robytfc provided good info. I've tried to chase this down before and failed; I'll have to take another stab at it.

If anyone has seen this in SSP, please let me know. Also, for those who are reproducing this issue: Does the problem go away if you chunkload your reactor? Does the problem reproduce every time the reactor unloads, or only occasionally?

**Comment by Silsec** [comment]
I've had this happen to me as well in single player mode. Every time I leave for long distance and come back all my fuel and energy was gone with the reactor shut off. Did alot of testing by taking out mods but nothing worked.  Then I found the problem, I had the reactor against a hill. After removing the dirt that was touching it every thing was fine.  It also resolve the problem when opening the reactors gui with tinkers construct tools which made the game crash.

**Comment by erogenousbeef** [comment]
@Silsec: Interesting! Can you give me some more details on how the reactor was set up? Was it just buried in other blocks, or were there also chunk boundaries involved? How much dirt was touching it, and where?

**Comment by Silsec** [comment]
List of mods  http://pastebin.com/mFdghpxQ
Crash report http://pastebin.com/aQE1M4nf

It was created one block into the floor. The back of the reactor was completely touching the dirt and a little bit on the sides. Only dirt was touching it nothing else. Let me know if you need any more info.

![2015-03-02_17 27 24](https://cloud.githubusercontent.com/assets/5997750/6452671/48e52abe-c105-11e4-8f43-bcdfc84294e2.png)
![2015-03-02_17 27 36](https://cloud.githubusercontent.com/assets/5997750/6452670/48dc1d52-c105-11e4-83f7-e8f03cf916c6.png)
![2015-03-02_17 27 46](https://cloud.githubusercontent.com/assets/5997750/6452675/48e5fa16-c105-11e4-947d-13a531c1eaaa.png)
![2015-03-02_17 28 02](https://cloud.githubusercontent.com/assets/5997750/6452672/48e58ee6-c105-11e4-937b-1ce803aaf00a.png)
![2015-03-02_17 30 00](https://cloud.githubusercontent.com/assets/5997750/6452673/48e595b2-c105-11e4-8c29-4c5f899e1107.png)
![2015-03-02_17 30 24](https://cloud.githubusercontent.com/assets/5997750/6452674/48e5bcfe-c105-11e4-82ef-ac29883bd08a.png)

**Comment by Silsec** [comment]
Unfortunately the problem has come back. I haven't made any changes to the reactor when I thought it was fixed. Right now I'm clueless.

**Comment by erogenousbeef** [comment]
Ok, so it's not the dirt then. Back to square one.

**Comment by Frontrider** [comment]
hmm its might not be a waste of time, but can you try it whitout ender io conduits?

**Comment by Silsec** [comment]
I've tried removing the conduits and everything else that was attached to it. Didn't help.  The reactor was powering about 7 machines and an ender quarry.

**Comment by erogenousbeef** [comment]
Total long shot - can you copy your world and try stripping out all non-BR mods, and see if the problem still happens?

**Comment by Silsec** [comment]
My world got corrupted so I had to delete it.  If I run into the problem again i'll do some more testing.

**Comment by Frontrider** [comment]
Forge makes a backup after you removed mods ;)

**Comment by erogenousbeef** [comment]
No new information in 20 days, closing.

**Comment by Gunner76th** [comment]
I would like to re-open this bug report, and assist in trying to trouble shoot this issue. After having read some of the reports on this thread, as well as having a member on my own server with this very same issue, I am suspect to thinking this is a chunk load/unload issue. I will be conducting some testing over the next several days, and providing as much feedback as I can, as well as photos of the events.

**Comment by erogenousbeef-zz** [comment]
The info in #492 appears to be distinct. Let's pursue the specific issue identified there. If further fuel-loss/fluid-loss events continue to occur, then we can reopen this issue.
