### ISSUE TITLE
[NPE-Crash] Using a Mekanism Logistical Sorter on a Cyanite Reprocessor causes a NPE-Crash

### ISSUE THREAD

**Issue by Lanse505** [erogenousbeef/BigReactors#417]
Using a Mekanism Logistical Sorter on a Cyanite Reprocessor causes a NPE-Crash

Crashlog: http://pastebin.com/ZcdfjekW

**Comment by erogenousbeef** [comment]
The stacktrace makes it look like the IC2 energy API is triggering updates when it shouldn't. I'll try to dig a bit deeper.

**Comment by Lanse505** [comment]
The reason for it calling "IC2 Energy API" is due to Mekanism having a stupid crashbug if IC2 energy API is not installed, and also we have IC2 in the pack.

**Comment by erogenousbeef** [comment]
Right, then closing this as a Mekanism issue.
