### ISSUE TITLE
Reactor not building; says only casing can be part of reactor frame

### ISSUE THREAD

**Issue by Arcnz** [erogenousbeef/BigReactors#421]
I was trying to make a 10x10x10 sized reactor, but the reactor never successfully turned into a multiblock. When I right-clicked to check what was the problem the message: "-481, 42, 140: -Only casing can be used as part of a reactor's frame", but the block -481, 42, 140 isn't even part of the reactor!

![2015-01-16_20 01 36](https://cloud.githubusercontent.com/assets/10481219/5775901/10e66942-9dbb-11e4-8aad-2dab058f5d2f.png)
![2015-01-16_20 01 43](https://cloud.githubusercontent.com/assets/10481219/5775902/118a715e-9dbb-11e4-8860-9ca7707ed15c.png)
![2015-01-16_20 02 31](https://cloud.githubusercontent.com/assets/10481219/5775903/11c8986c-9dbb-11e4-8b65-500722ffa6db.png)

**Comment by Kubuxu** [comment]
You may not place ports/controllers at the edges. Only casing blocks.

**Comment by erogenousbeef** [comment]
Yes, as @Kubuxu said, only casing can be used for the reactor's frame - that's the outline of the cube. Ports, controllers and other utility blocks must be placed inside one of the flat faces (the areas you've currently filled entirely with reactor glass).
