### ISSUE TITLE
Clientside crash

### ISSUE THREAD

**Issue by Keridos** [erogenousbeef/BigReactors#422]
One player on my server gets this crash ocassionally: http://pastebin.com/snFEiAFd

**Comment by erogenousbeef** [comment]
Your player neeeds to increase permgen size and/or the amount of memory available to Java.

**Comment by Keridos** [comment]
Funny is, he had problems with his internet, his permgen space was 256/512 MB, so plenty. And we were both in the same dimension, just he crashed over and over again. Maybe wobbly internet makes your reactor produce a clientside memory leak?

**Comment by Kubuxu** [comment]
As you can see: ```Caused by: java.lang.OutOfMemoryError: PermGen space``` And I doubt that @erogenousbeef  uses ASM and/or class generation anywhere, so it is not BigReactors issue.
