### ISSUE TITLE
Big reactors is crashing me but I have to have it!!!!

### ISSUE THREAD

**Issue by WeedPig** [erogenousbeef/BigReactors#424]
this is my crash report once I add big reactors when I delete big reactors everything is well
pastebin.com/MG5S8qus

**Comment by erogenousbeef** [comment]
Your version of CofHCore is 3.0.0b6. Big Reactors 0.4.1A2 requires CofHCore 3.0.0b9 or newer.

Upgrade CofHCore to fix this.
