### ISSUE TITLE
Cyanite Reprocessor Spawning Randomly

### ISSUE THREAD

**Issue by Kylorip** [erogenousbeef/BigReactors#425]
We discover with my friends that on our server crashes were due to ticking entity which gave us coordinates and when we go to this coordinates we discover that a lot of Cyanite reprocessor had spawn randomly on our map for no reason at all but it can cause world corruption and we already had to change our map once and on the new map it's starting again we just discover some cyanite reprocessor floating in the air. 
Can you help us ?

**Comment by erogenousbeef** [comment]
I need to know, at minimum:
* Version of Big Reactors, CoFHCore and Forge
* Which other mods you have installed

This sounds like an ID conflict, wherein you had some blocks from one mod, then removed that mod at the same time that you added BR. I suggest you try removing BR and starting the server, which will reset all BR blocks to air. Next, shut the server down and re-add BR. (Do _not_ make any other changes to your pack when doing this.)

**Comment by Kylorip** [comment]
Thanks for your fast anwers so as you've asked here are the:

-Version of Big Reactors 0.4.0rc10
-Version of CoFHCore 3.0.0B8-36
-Version of Fore 10.13.2.1236

And the list of mods installed + verisons:
-1.7.10_AM2_1.4.0.005.jar
-AdminCommandsToolbox-0.0.2a_1.7.10.jar
-AdvancedSolarPanel-1.7.10-3.5.1.jar
-appliedenergistics2-rv1-stable-1.jar
-AsieLib-1.7.10-0.3.2.jar
-ATG-1.7.2-0.10.0.jar
-backpack-2.0.1-1.7.x.jar
-Baubles-1.7.10-1.0.1.8.jar
-bdlib-mc1710-1.4.3.14.jar
-BiblioCraft[v1.8.2][MC1.7.10].jar
-Blood Magic-v1.2.0b(1.7.10).jar
-Botania r1.3-135.jar
-buildcraft-6.0.18.jar
-Carpenter's Blocks v3.3.0 - MC 1.7.10.jar
-ChickenChunks-1.7.10-1.3.4.14-universal.jar
-Chisel-1.7.10-1.5.7.jar
-CodeChickenCore-1.7.10-1.0.4.29-universal.jar
-CodeChickenLib-1.7.10-1.1.1.104-universal.jar
-CoFHLib-[1.7.10]1.0.0B7-29.jar
-ComputerCraft1.65.jar
-Computronics-1.7.10-1.1.0.jar
-denseores-1.4.2.jar
-DragonAPI 1.7.10 V2.jar
-Enchiridion-1.7.X-1.2b.jar
-EnderIO-1.7.10-2.1.6.250.jar
-EnderStorage-1.7.10-1.4.5.24-universal.jar
-ExtraCells-1.7.10-2.1.12b9.jar
-extrautilities-1.1.0k.jar
-FlatSigns-1.7.10-universal-2.0.0.17.jar
-FluxedFeederUnit-MC1.7.10-1.0.0.jar
-forestry_1.7.10-3.1.1.4.jar
-ForgeMultipart-1.7.10-1.1.0.309-universal.jar
-GraviSuite-1.7.10-2.0.3.jar
-Hats-4.0.1.jar
-ic2nc-1.7.10-1.7.10.08.jar
-iChunUtil-4.0.0.jar
-immibis-core-59.0.3.jar
-immibis-peripherals-59.0.0.jar
-industrialcraft-2-2.2.647-experimental.jar
-IOPeripheral-1.7.10R1.3.jar
-ironchest-1.7.10-6.0.62.742-universal.jar
-Jabba-1.1.4_1.7.10.jar
-logisticspipes-0.8.1.72.jar
-malisiscore-1.7.10-0.9.9.jar
-malisisdoors-1.7.10-1.2.1.jar
-Mantle-1.7.10-0.3.2.jar
-Mariculture-1.7.10-1.2.3d-146.jar
-Mekanism-1.7.10-7.1.1.118.jar
-MekanismGenerators-1.7.10-7.1.1.118.jar
-MekanismTools-1.7.10-7.1.1.118.jar
-Minechem-1.7.10-5.0.5.134.jar
-MinecraftLoader 0.1.3 mc1.7.10.jar
-MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar
-MineTweaker3-1.7.10-3.0.9B.jar
-MobiusCore-1.2.3_1.7.10.jar
-ModularPowersuits-0.11.0.174.jar
-Morpheus-1.7.10-1.5.24.jar
-natura-1.7.10-2.2.0.1.jar
-neiaddons-mc1710-1.12.3.11.jar
-NotEnoughItems-1.7.10-1.0.3.62-universal.jar
-Numina-0.4.0.98.jar
-ObsidiPlates-1.7.10-universal-3.0.0.18.jar
-OpenBlocks-1.7.10-1.3-snapshot-434.jar
-OpenComponents-MC1.7.10-0.2.0.20-universal.jar
-OpenComputers-MC1.7.10-1.3.6.69-universal.jar
-OpenEye-0.6-1.7.10.jar
-OpenModsLib-1.7.10-0.6-snapshot-224.jar
-OpenPeripheralAddons-1.7.10-0.2.0-snapshot-122.jar
-OpenPeripheralCore-1.7.10-0.5.0-snapshot-142.jar
-Opis-1.2.3_1.7.10.jar
-Pam's HarvestCraft 1.7.10c.jar
-PlanetguyLib-1.0.jar
-PneumaticCraft-1.7.10-1.2.13-28-universal.jar
-ProjectRed-Base-1.7.10-4.5.1.51.jar
-ProjectRed-Compat-1.7.10-4.5.1.51.jar
-ProjectRed-Integration-1.7.10-4.5.1.51.jar
-ProjectRed-Lighting-1.7.10-4.5.1.51.jar
-ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar
-ProjectRed-World-1.7.10-4.5.1.51.jar
-QuarryPlus-1.7.10LBC-2.0-RC8.jar
-Railcraft_1.7.10-9.3.3.0.jar
-RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar
-RefinedRelocation-1.7.10-1.0.6h.jar
-RemainInMotion-2.1.4.jar
-RotaryCraft 1.7.10 V2.jar
-rotateableblocks-17x-build-9.jar
-RouterReborn-1.7.10-1.1.6-universal.jar
-slick-util.jar
-StevesCarts2.0.0.b18.jar
-StevesFactoryManagerA93.jar
-Sync-4.0.0.jar
-TConstruct-1.7.10-1.7.1.jar
-Thaumcraft-1.7.10-4.2.1.4.jar
-ThaumicTinkerer-2.5-1.7.10-158.jar
-ThermalExpansion-[1.7.10]4.0.0B6-16.jar
-ThermalFoundation-[1.7.10]1.0.0B3-8.jar
-TMechworks-1.7.10-0.2.9.jar
-Translocator-1.7.10-1.1.1.12-universal.jar
-WR-CBE-1.7.10-1.4.1.6-universal.jar

Next time the error happends we'll try your solution of removing Big Reactors to restart the server
