### ISSUE TITLE
Turbine Fluid Port

### ISSUE THREAD

**Issue by Rangegod16** [erogenousbeef/BigReactors#427]
I'm not sure if this is a bug, or a function of the Turbines that I was unaware of. I wasn't able to find any information regarding it, and it's causing me quite bit of confusion.

Is there a limit to the number of Turbine Fluid ports that will draw steam at once? In my current set up, I have a large number of them but only five (The ones marked with red in the image) are actually pulling steam into them.

Each port is set up identically. A large drum is pushing steam using Extra Utilities Transfer Nodes into a smaller drum next to each port, which in turn has a liquid transfer node (each with a stack upgrade), connected to the port below it. 

Yet only 5 of them actually pull steam (tested by removing the transfer pipe that is supplying the drums. Anyway. Is this a bug, or a feature? 
 
http://i62.tinypic.com/2ecpxed.png

**Comment by erogenousbeef** [comment]
Turbines can only accept an amount of steam equivalent to their internal tank size each tick, which they will then empty. Once the steam tank is full, it won't matter how many inlet fluid ports you add.
