### ISSUE TITLE
Pipe positioning glitch

### ISSUE THREAD

**Issue by thexaxoo** [erogenousbeef/BigReactors#432]
There is a glitch with pipes from BuildCraft
here is a connection right before world save and exit:
https://i.imgur.com/lnHPfH5.png
and after world loading:
https://i.imgur.com/sgS1zmT.png
The only way for this to not happen is:
https://i.imgur.com/NlmnQiL.png

Thanks!

**Comment by erogenousbeef** [comment]
Buildcraft problem. They should be listening for neighbor tile entity updates, not just block updates. It's more efficient to send neighbor tile entity updates.
