### ISSUE TITLE
Turbines detect metal blocks outside the casing as loads

### ISSUE THREAD

**Issue by syntaxaire** [erogenousbeef/BigReactors#436]
We had a 8 vertically oriented turbines with copper and tin blocks for beacon bases stacked directly on top of the upper casings (outside the multiblock structure) of 6 of them. The turbines were 80 blade with 32 ludicrite blocks being fed 2B/s of steam for 1800rpm operation. The 6 turbines with extra metal blocks outside the casing all got stuck at 1167rpm. Removing the metal blocks from above the turbine, breaking a turbine block and replacing it allowed it to reach 1800rpm.

**Comment by erogenousbeef** [comment]
Well, I'll be damned. Good work finding this. It'll probably fix #232 as well.

**Comment by syntaxaire** [comment]
Thanks. This was on Progress, you should drop in some time :)
