### ISSUE TITLE
Incorporate Costs, Risks & Consequences to Avoid Obsoleting Other Power Options

### ISSUE THREAD

**Issue by Eunomiac** [erogenousbeef/BigReactors#437]
**Disclaimer:**  I know this is being discussed in other places, but I think it's a good idea to have an issue open on the topic:  It's an important one, and an open issue ensures that (what I hope will be) a fruitful discussion won't be lost to the nether-pages of a discussion forum.

While BigReactors is, in my opinion, the most interesting and exciting power generation mod out there, it too-quickly becomes the *only* power generation option.  Even passively-cooled reactors generate power an order of magnitude more quickly and more efficiently than the mod's nearest competitors, rendering those mods---and all the gameplay surrounding their power generation options---obsolete.   

> Now---and this is important---I *fully* understand that many of you do not think there's anything wrong with this (i.e. "if you think it's OP, don't use it").  This is why I think any such balancing efforts should be configurable, allowing people on both sides of The Great Balance Debate to enjoy BigReactors in the way that best suits them.

As but one example of what I mean, look at the fun generators in ExtraUtilities---TNT, Pink, Culinary and (especially) Potions offer new applications for underused items, each with its own unique automation "puzzle" to solve.  Yet (as a playthrough of Agrarian Skies or ME^4 will quickly demonstrate) they're strictly trumped in every way by access to a tier-one Reactor.  This shuts down choice and gameplay in the area of power generation.

I have one main suggestion on how BigReactors could remain king-of-the-castle when it comes to power generation, while restoring the gameplay that's lost when it trumps the other options out there:  

**Big Reactors = Big Power... and** ***Only*** **Big Power.**    

Specifically:

1. Even the smallest Reactor generates a lot of power.
2. All that power must be *used* to avoid consequences (ranging from fuel waste and inefficiency, up to meltdowns and craters).

I suggest the following as options that, in tandem, would realize the above goals.  (Oh, please let me know if any of these are already in the development pipeline, and I'll edit them out to keep this wall-of-text focused on the suggested *new* features.)

* **No Small "Big"Reactors**:  Increasing the minimum horizontal dimensions to 5 and the minimum number of fuel rods to 3 would (when combined with some of the suggestions below) increase the minimum possible power output of Reactors, ensuring they are only appropriate for large-scale power needs.
* **Increased Activation Time**:  Much like a RailCraft Boiler, it takes a Reactor time to power up.  During its "spooling up" period, fuel consumption is extremely high and power generation is extremely low, killing efficiency.  Frequently toggling a Reactor on and off to control power output becomes unfeasible.
* **Limited Control Rods**:  Control Rods have only limited ability to reduce the power output of a Reactor:  Perhaps at 99% insertion, power generation is cut in half (100% can still be "full shutdown"---faster than turning the Reactor off, but with fuel waste---for use as an emergency valve).  This allows some tuning, without allowing a Reactor to play the role of a Stirling Engine.
* **Dangerous Buffered Power**:  As the Reactor's internal buffer fills, heat increases and the Reactor burns fuel faster and less efficiently.  Once the Reactor's buffer reaches capacity, there's nowhere else for that excess power to go, and the heat it generates becomes destructive:  interior coolant vaporizes, causing the problem to snowball into a cascading series of failures that ultimately end in one hell of a spectacular explosion.
* **Turbine Speed Limits**:  A turbine can only spin so quickly before its own inertia tears it apart---destroying the turbine housing, rotor, and the blocks comprising the rotor coil.  This is a less destructive event than a Reactor meltdown... but it will quickly lead to a Reactor meltdown if the steam being generated is allowed to build up.
* **Increased Impact of Decoupling**:  Disengaging a turbine's induction coils effectively removes almost all of the friction on its rotor blades, resulting in a much faster---and more dangerous---spin.  A turbine running at maximum efficiency (1800 rpm) will quickly tear itself apart, while turbines running at slower speeds have a bit more leeway---throwing another factor to consider on the 900 vs 1800 decision.
* **Less-Friendly Decoupling**:  Decoupling a turbine rotor does one thing: stop it from generating power, thus avoiding the consequences of accumulating too much unused energy.  However, fuel consumption is unchanged: the connected Reactor continues to gobble up fuel and water, oblivious to the coupling state of the turbine.

So what do you think of these suggestions?  Any other ideas on reducing the space BigReactors occupies in the power-gen game, so that there's room for it to exist alongside alternate power generation options?

**Comment by erogenousbeef** [comment]
No.

**Comment by erogenousbeef** [comment]
To elaborate: Use the config options if you feel the mod doesn't fit your vision of balance.
