### ISSUE TITLE
Crash with AE interaction

### ISSUE THREAD

**Issue by devryb** [erogenousbeef/BigReactors#438]
Got this crash earlier and ran visualvm as it also hung the server.  Appears to be some storage component from AE interacting with the reactor?

http://mc.devcoftb.net/crashes/RRME/crash-2015-02-09_00.43.04-server.txt

http://puu.sh/fFVUh/5911d00910.png

Version: 0.4.1A2

**Comment by erogenousbeef** [comment]
Can you reproduce this with only AE2 and BR? Is this crash consistent?

**Comment by devryb** [comment]
I have not seen this issue again so it may just be a one off occurrence.  I'm not even sure what exactly the setup in question looks like that crashed this due to a lack of coordinates in the report.
Will let you know if it happens again.
