### ISSUE TITLE
power tap bug? no canection to any cable of any kind

### ISSUE THREAD

**Issue by TOTHEMOON11** [erogenousbeef/BigReactors#441]
I love the mod but i found a bug that well makes it useless after you build the reactor you have the power tap but when you power up you make RF but you cant git it out even with a power tap no energer or "RF" will go into anything plz help me im using : CoFHCore-[1.7.10]3.0.0B6-32, and: big reactors-0.4.1A2 ill and a screen shot aswell someone plz help me
![2015-02-13_11 34 26](https://cloud.githubusercontent.com/assets/10995334/6191028/6961cd86-b374-11e4-97b1-553df64d5a93.png)
![2015-02-13_11 34 20](https://cloud.githubusercontent.com/assets/10995334/6191029/6cf569a8-b374-11e4-9003-9d75f030ca16.png)
![2015-02-13_11 33 57](https://cloud.githubusercontent.com/assets/10995334/6191036/73f409c6-b374-11e4-99d5-2c7a9d358efd.png)

**Comment by erogenousbeef** [comment]
Please read the requirements on www.big-reactors.com. Big Reactors 0.4.1A2 requires CoFHCore-3.0.0B9 or above.
