### ISSUE TITLE
[COMPUTER CRAFT] Can't use bigreactor computer port

### ISSUE THREAD

**Issue by leo91000** [erogenousbeef/BigReactors#443]
Hi,
I am having trouble with big reactor computer port. I don't know if this is the place to post.
Here is my setup :
http://i.gyazo.com/865a8ac3a31480894de1214a64b5a158.png
http://i.gyazo.com/9dc6b48e54b43f684884db194c87dbf4.png
What program I did :
http://pastebin.com/XwKcHhdq
Error :
http://pastebin.com/v6u1wx75

**Comment by erogenousbeef** [comment]
This is not a Big Reactors problem. I suggest asking for help on a Computercraft forum.
