### ISSUE TITLE
Unable to access reactor - port is not connected

### ISSUE THREAD

**Issue by da404lewzer** [erogenousbeef/BigReactors#449]
Today I noticed my console was spitting out a ton of stack traces. I then noticed one of my log files was SEVERAL GIGS in size due to the constant stack traces being dumped out. 

Here's the stack trace it kept repeating over and over again:
http://pastebin.com/jcpf41nR

It seems to only happen after a server restart and breaking the reactor and putting it back fixes it. This is a real problem due to the fact that everyone has a reactor and everyone controls it via ComputerCraft.

In case you're curious, I'm playing "The 1.7.10 Pack" on the Tekkit launcher and the latest version includes the following mod versions:
BigReactors - 0.4.1A2
ComputerCraft - 1.65

Love the mod, it's my favorite source of power!

**Comment by erogenousbeef** [comment]
What's likely happening is that you have a reactor somewhere spanning two chunks, one of which gets loaded and loads a CC program, which then tries to access the partially-loaded reactor. It then fails.

As per the [BR API documentation] (http://big-reactors.com/#/api.computer), you should be calling `getConnected` before other BR CC methods.

**Comment by da404lewzer** [comment]
This is a server with several people all doing their own thing and I can't hover over every person ensuring they position their reactors inside a chunk boundary or call the correct method first. I believe you have the power to detect this error and suppressed it. The console spam is contributing to wasted disk space and it's slowing down the server. Please reconsider fixing the problem and not just dismissing it.

**Comment by GreatHolyCow** [comment]
I to am having this problem, I don't think its my job to police my users scripts constantly. If you cant fix simple errors in your mod whats the point in keeping it in my pack. This needs to be addressed. If Big Reactors cant fix the memory leak issues related to this lag then it shall just simply be removed no need to play with a glitchy mod. You have to remember computer craft support people make all kinds of scripts and admins cant constantly police them to make sure they are doing something specific. The mod should catch this glitch and spit out a trace and trap it before it just loops endlessly I shouldn't go from 5-10Mb log files to 5Gb log files

**Comment by erogenousbeef** [comment]
@da404lewzer - Fair point. Just took a look and this should be a two-liner, so I'll rush out an 0.4.2A2 with a fix.

@GreatHolyCow - You'll find civility gets you a lot further on this issue tracker than otherwise.

**Comment by da404lewzer** [comment]
My server's SSD thanks you very much. Looking forward to the update!
