### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by Samuell95** [erogenousbeef/BigReactors#451]
Updated to newest version 0.4.2A2 , and repeatly crashing

Crashlog: http://icrazy.eu/code/raw/2cn69rzY

**Comment by erogenousbeef** [comment]
Looks like there's two problems here.

(1) The true problem is that there's some bug in ComputerCraft whereby a clientside field is being accessed on the server. I suggest you report this to the ComputerCraft bug tracker.

(2) BR is triggering a chunkload on the server when validating a machine. This is a performance problem, really, and shouldn't crash anything.

**Comment by Samuell95** [comment]
Thanks for the fast reply. I updated Computercraft version from 1.72 to 1.73 and working :)
