### ISSUE TITLE
BUG :Big Reactors : Making Yellorium from Blutonium

### ISSUE THREAD

**Issue by Trigger2** [erogenousbeef/BigReactors#452]
I am playing Direwolf 20 1.7 Pack and when you put Blutonium in a reactor and  eject the Fuel at the reactor access port you'll get yellorium instead of Blutonium.

Sorry for my bad English and I hope it'll be fixed soon

**Comment by erogenousbeef** [comment]
This was fixed for BR 0.4.0rc6 in commit 9789231ace646ef6eef23e5b132650de9e808e2a . Which version of BR are you using? If you're using an older one, you'll have to upgrade.

**Comment by Trigger2** [comment]
-----Ursprüngliche Nachricht-----
 Von: "Mr. E. Beef" [notifications@github.com]
 Gesendet: Fr. 27.02.2015 11:28
 An: "erogenousbeef/BigReactors" [BigReactors@noreply.github.com]
 Kopie: "Trigger2" [robin.kuehr@freenet.de]
 Betreff: Re: [BigReactors] BUG :Big Reactors : Making Yellorium from Blutonium (#452)

This was fixed for BR 0.4.0rc6 in commit 9789231 . Which version of BR are you using? If you're using an older one, you'll have to upgrade.
—
Reply to this email directly or view it on GitHub.
-----Ursprüngliche Nachricht Ende-----
 
Hi,
thanks for your answer and I am using version 0.4.0rc10



---
Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse mitnehmen! Rundum glücklich mit freenetMail

**Comment by moTechPlz** [comment]
I can reproduce this bug, video; https://vid.me/8oT5

mods used;
- BigReactors-0.4.2A2.jar
- CodeChickenCore-1.7.10-1.0.4.35-universal.jar
- CodeChickenLib-1.7.10-1.1.3.127-universal.jar
- CoFHCore-[1.7.10]3.0.0RC5-207.jar
- ForgeMultipart-1.7.10-1.1.1.323-universal.jar

**Comment by erogenousbeef** [comment]
Oh, derp, __blutonium__ into yellorium. Yes, this is a known issue. Currently, it's intended behavior, as it's a consequence of the incomplete state of the internal reactant simulation. It will be fleshed out in future versions, although I don't have a precise answer as to when.

(Basically, blutonium is aliased to yellorium when being injected into a reactor as opposed to being considered a separate fuel type.)
