### ISSUE TITLE
Bug: My 21x21 reactor says invalid block on an air block on top of the corner of outside edge of my reactor V0.4.1A2

### ISSUE THREAD

**Issue by Zenrap518** [erogenousbeef/BigReactors#453]

**Comment by Zenrap518** [comment]
sry if i dont make sense

**Comment by Frontrider** [comment]
picture

**Comment by erogenousbeef** [comment]
A picture of the error would be helpful, as would the version numbers for Forge and CoFHCore.

**Comment by erogenousbeef** [comment]
No new information in over a week, closing. Please reopen this issue if you can collect the above information.

**Comment by Frontrider** [comment]
Thinking: have you placed the controller and the ports on the frame? If yes put them to the walls of the reactor.
