### ISSUE TITLE
Big Turbine is breeding?

### ISSUE THREAD

**Issue by Rothmaw** [erogenousbeef/BigReactors#458]
First time I saw the bug was today affects both of my turbines. [Image of bug](https://imgur.com/a/17KBN) The hearts don't seem to stop either.

**Comment by Frontrider** [comment]
tried it whitout resource pack?

**Comment by Frontrider** [comment]
https://github.com/erogenousbeef/BigReactors/issues/457
never mind

**Comment by erogenousbeef** [comment]
Easter egg.
