### ISSUE TITLE
Add links to Crafting Guide (http://crafting-guide.com)

### ISSUE THREAD

**Issue by andrewminer** [erogenousbeef/BigReactors#463]
I've been working on a project to make it easier to deal with complex mods (especially tech mods), and I recently added support for Railcraft. The gist of the site is that you tell it what item(s) you want to make, and it will figure out all the raw ingredients you need along with step-by-step instructions. For example, [here's what you'd need](http://crafting-guide.com/craft/23.reactor_casing:reactor_control_rod:reactor_controller:reactor_coolant_port:reactor_redstone_port:yellorium_fuel_rod) to make the smallest possible "big" reactor.

The maintainers of mods I've added (e.g., BuildCraft / Applied Energistics / EnderIO) have found it useful to include links to Crafting Guide in their official documentation, and I was hoping you would feel the same.

**Comment by andrewminer** [comment]
Any update on adding that link?  It would be much appreciated!

**Comment by erogenousbeef** [comment]
I'll do this during Easter weekend; I've not been home in a month. Sorry for the delay. :(

**Comment by redwood-labs** [comment]
No problem!  Enjoy your trip!

**Comment by erogenousbeef** [comment]
Done! It's on the wiki's front page.

**Comment by andrewminer** [comment]
Thanks!
