### ISSUE TITLE
Multiplier settings in the config don't work as expected

### ISSUE THREAD

**Issue by Glockshna** [erogenousbeef/BigReactors#464]
I figured this was some strange interaction with some of my mods so I went to a clean forge install with only:

Forge 10.13.2.1291
Big Reactors 0.4.2A2 
COFH Core 3.0.0RC7-211

The power multiplier config option behaves strangely. I tested the following settings:

Control: Default config
262 RF/t

Power Multiplier: 2

Expected: 524RF/t 
Got: 1.03 KiRF/t (~4x)

Mult: 3

Expected: 786 Rf/t
Got: 2.31 KiRF/t (~8x)

Mult: 4

Expected: 1048 Rf/t
Got: 4.1 KiRF/t (~15x)

Mult: 10

Expected: 2.6 KiRF/t
Got: 26 KiRF/t (~100x)

It looks like the config is somehow exponential.

**Comment by erogenousbeef** [comment]
Are you changing just `powerProductionMultiplier`, or both `powerProductionMultiplier` and `reactorPowerProductionMultiplier`? Both are applied, so if you're changing both, then your results make sense.

**Comment by JasonMcRay** [comment]
I can confirm this issue. It works now diferently than in versions before.
In all tests I have `reactorPowerProductionMultiplier=1.0`

I have a maximum efficiency BR turbine in my base (32 ludicrite coils, 80 blades)
When I have set the `powerProductionMultiplier=1.0` the energy I am getting is: 28kRF/t
When I set `powerProductionMultiplier=0.6` in previous versions (before 0.4.2A2) i was getting 17kRF/t (that is indeed 60% of the 28k), but now in 0.4.2A2 I get only 9kRF/t (which is about 30%).
When I set the `powerProductionMultiplier=0.8` I am at 17kRF (but it should be higher, since this is not 80%).

**Comment by erogenousbeef** [comment]
`powerProductionMultiplier` is applied _both_ to the reactor and to the turbine, hence why you're seeing exponential results. Raising `powerProductionMultiplier` raises both the amount of raw energy generated by the reactor (and thus raising the amount of steam produced) and also raises the amount of energy generated by a turbine from a unit of steam.

It sounds like what you really want is to change either `reactorPowerProductionMultiplier` _or_ `turbinePowerProductionMultiplier`, but not both.

**Comment by Glockshna** [comment]
I was only changing PowerProductionMultiplier, and I was not using steam turbines. Just a basic 3x3 reactor in a field with nothing else. Is that also intended?

**Comment by erogenousbeef** [comment]
No, that's odd. Also, in the future, please explain your setup in your initial bug report.

**Comment by erogenousbeef** [comment]
Oh, wow.

```
powerProductionMultiplier = (float)BRConfig.CONFIGURATION.get("General", "powerProductionMultiplier", 1.0f, "A multiplier for balancing overall power production from Big Reactors. Defaults to 1.").getDouble(1.0);
reactorPowerProductionMultiplier = (float)BRConfig.CONFIGURATION.get("General", "powerProductionMultiplier", 1.0f, "A multiplier for balancing reactor power production. Stacks with powerProductionMultiplier. Defaults to 1.").getDouble(1.0);
turbinePowerProductionMultiplier = (float)BRConfig.CONFIGURATION.get("General", "powerProductionMultiplier", 1.0f, "A multiplier for balancing turbine power production. Stacks with powerProductionMultiplier. Defaults to 1.").getDouble(1.0);
```

You're seeing exponential results because it's reading `powerProductionMultiplier`'s value in for all of the multipliers. Herp a derp. Fixing.
