### ISSUE TITLE
[SUGGESTIONS] Boilers, Circulators, Shutdown effects, Backup Power, Sounds & Condensers

### ISSUE THREAD

**Issue by chris6273** [erogenousbeef/BigReactors#465]
Hi,

I've been using this mod for a very long time for various purposes and there are a few features I'd like to suggest which could make the mod more complete and slightly more challenging for some.

The first is adding boilers/heat exchangers; most/all reactors in reality use boilers which the hot gases within the reactor are passed through. These gases heat a separate circuit of water to steam which is carried to the turbines.
At the moment I've found all I have to do is 'plug' a pipe into a fluid outlet/inlet and it caries the steam directly to the turbines - This is quite unrealistic.

The second is adding Gas Circulators. In reality these are extremely important in ensuring gases passing through the core of the reactor are circulated around the boilers so that heat can be carried away. Adding these would make for a more realistic and challenging mod because you'd have to ensure you have a reliable and continuous stream of energy to keep the gas circulated.

The third goes hand in hand with the previous two suggestions; shutdown effects. I couldn't think of what else to call this but what I mean is having the reactor requiring cooling from gas circulators after shutdown to prevent overheating. Dropping control rods in some cases is way too easy and quick. This could also lead onto the next suggestion; backup power.

Forth; backup power. This is the main feature I'd like to suggest having a presence in the mod and would require the second suggestion. It would require the reactor/circulators to have a continuous supply of power for cooling in the case of the turbines being tripped or turned off. Modern plants have separate diesel/gas turbine backups to ensure vital equipment is powered at all times. This could be achieved with a simple redstone circuit, activating the backup system if the turbine isn't on.

Fifth; Sounds. Another big feature I think is missing from the mod is turbine sounds. Having the ability to add or have pre-added sounds would be amazing. I have a few I'd add but there's no way I can see to add sounds. It would make the mod more immerse.

Sixth and finally; Condensers. At the moment steam which comes out of turbines is immediately (Somehow) turned to water to be passed through the reactor again. I believe there's an opportunity here for a new multi-block structure which has the responsibility of condensing the used steam into water to be passed through the circuit again. Expanding on this even more; in reality condensers require a source of water, usually seawater, to remain cool which is in a separate circuit altogether.

I know it's a long list but I've always been taught "If you don't ask, you don't get".

Just some suggestions from someone who has an active interest & knowledge in nuclear power in reality :).

**Comment by erogenousbeef** [comment]
I appreciate your enthusiasm. Heat exchangers are already in "active" development for 0.5 (see the `dev-0.5` branch) and on the roadmap. Sounds are also on the roadmap.

I'll have to think a lot about the other bits. Condensers I decided against long ago, as it adds no new interesting design possibilities - it's just a "build a cube of X size for Y flow" deal.

Taking a step back to look at the bigger picture, each new module/machine added to the mod has to fit in with the rest of the system as an _optional_ component. People who don't want to deal with the added hassle/complexity shouldn't be forced to do so; those who opt-in should be rewarded (usually with better peak output or efficiency).

Anyhow, thanks for the writeup. :)
