### ISSUE TITLE
Crazy turbine rotor speed

### ISSUE THREAD

**Issue by Jackssss** [erogenousbeef/BigReactors#469]
Hi, i use big reactor in FTB Ultimate, (big reactor release 0.4.2A2), and i don't know if it's normal, but when i start a turbine, the animation of rotor begin normaly slow and quickly the speed of the spin go so fast, while the turbine controler display just 500rpm. And it's the animation of spin its like 50000rpm :(. When i look other videos on youtube, the rotor turn slowly, even at 2500rpm.

It's normal ?

**Comment by erogenousbeef** [comment]
The turbine rotor speed in earlier versions of 0.4 was too slow, actually. "Just" 500 RPM is 8.3 rotations _per second_, or one rotation every 120 milliseconds (roughly every 5-10 frames at a smooth framerate).

So yes, it's normal.
