### ISSUE TITLE
Unknown problem, Infinity server crashing

### ISSUE THREAD

**Issue by ajthemacboy** [erogenousbeef/BigReactors#470]
Hi. Yesterday my FTB Infinity server entered a crash loop and the log mentions big reactors. I asked on the FTB forum but we couldn't solve the problem. 

Here is the server log: http://pastebin.com/Ah68m5L5

Here is the crash log: http://pastebin.com/wGnNXyYx

Both are not full logs, I am SSHing into the host and can't copy them all in Vim.

**Comment by ajthemacboy** [comment]
By the way, one of my players mentioned breaking a BigReactor with a TCon hammer crashing the server. If this IS the issue, is it possible to release an update to the mod that is serverside only, so Infinity players can keep playing?

**Comment by erogenousbeef** [comment]
Looks like there's a corrupt reactor somewhere on your server, but it really shouldn't loop-crash.

As for the TiCon issue, it's tracked in another open ticket. I will work on it when I have time, but I've been away on business for over a month now, so I'd recommend wiping the reactors on your server if this is blocking you from playing.

**Comment by ajthemacboy** [comment]
I have tried removing BigReactors with no luck! I figured this would delete all reactor blocks, but I'm still getting this crash log (this time I was able to get the full one): http://pastebin.com/CNrTcCAd

**Comment by ajthemacboy** [comment]
Even after I removed the reactor in MCEdit, the problem persists.

**Comment by erogenousbeef** [comment]
That log shows that BR is still installed. There's a corrupt block somewhere.

**Comment by ajthemacboy** [comment]
I have removed BigReactors, you clearly don't believe me. 

http://gyazo.com/b505ffe11bfd532013accfc37d71746d

That's my mods folder...

**Comment by ajthemacboy** [comment]
Here is the FULL server LOG, since the crash report doesn't seem to say much:

https://www.dropbox.com/s/t6xc79ngfzk8ywo/latest.log?dl=1

**Comment by erogenousbeef** [comment]
Your most recent crash log clearly lists BR as installed. I'll take a look at the full log later - I'm about 3 minutes from boarding my next flight.

**Comment by ajthemacboy** [comment]
Perhaps the crash report isn't being saved anymore, and that's an old one?

**Comment by ajthemacboy** [comment]
We just reset the world. I've looked at the other issues, though, and it seems this has been a problem for a while. We think we're just going to remove BigReactors until you fix the issue with Tcon.
