### ISSUE TITLE
[Bug] Water Bottle Duplication

### ISSUE THREAD

**Issue by artdude543** [erogenousbeef/BigReactors#471]
The liquids from Big Reactors are being registered as `Material.water` thus allowing players to create a unlimited water source from the fluids. This affects modpacks which rely on making the player think about hydration and so forth, as the player just needs to use one of your fluids and can just keep taking all the water they want.

Would it be possible for you to create a custom fluid material to register your fluids under to prevent this issue from happening?

**Comment by erogenousbeef** [comment]
How are your players gaining access to those fluids? They're placeholders, not intended for actual use.

The BR fluids aren't exposed anywhere via recipes in BR itself; to my knowledge, you can only obtain them via admin actions.

**Comment by artdude543** [comment]
I'm not totally sure myself I will have the ask the players of my modpacks. But I know some mods allow you to pump the fluid's into the world, and some other mods are registering your blocks to be smeltable  _(Example being AOBD)_ which then you can pump the fluid into the world ; so this could be the method that they are using. I understand that the fluids are not "survival" getable but I'd thought I would bring this up to you.

Also to add on to this issue, if you cast your fluid's into a bucket (Using tinkers) you can place the fluid into the world as the material and upon picking up you get back a bucket of water.

**Comment by erogenousbeef** [comment]
The actual bug, then, is that other mods are erroneously exposing placeholder/debug content that's not intended for consumption. Please inform them.

**Comment by Funwayguy** [comment]
It should not be left up to other mod developers to fix YOUR liquids that are registered wrong. This could fixed with half a line of code (change the material type). It is also not feasible for developers to have to ask every other developer whether certain liquids/items/blocks should or shouldn't be accessed from their mods just because they left unfinished placeholder/debug content there.

**Comment by erogenousbeef** [comment]
I disagree. If you're integrating with another mod, you damned well need to know that mod - including whether something should be made user-accessible or not.

You don't expect an external mod to make creative mode items accessible either - this is an identical case.
