### ISSUE TITLE
Possible computercraft issue, the api what you use might be outdated

### ISSUE THREAD

**Issue by Frontrider** [erogenousbeef/BigReactors#472]
We get some computercraft errors whitch are related to some mod using old api. We're not sure what's going on, but i think you should investigate. Just to be safe.

**Comment by erogenousbeef** [comment]
What are the errors you're getting? What version of BR are you using? What version of Computercraft are you using?

**Comment by Frontrider** [comment]
Server updated, issues gone. Lot of people used computercraft controlled reactors.

**Comment by Frontrider** [comment]
Got back to my computer, seems to be fixed.
