### ISSUE TITLE
Maintain project on minecraft.curseforge.com as well

### ISSUE THREAD

**Issue by RAnders00** [erogenousbeef/BigReactors#473]
It would be a nice piece of infrastructure that would your users to stay up to date with the latest Big Reactors using the Curse Client. It has such things now, you can create your own modpacks and auto-update them. It would also reduce usage of outdated BigReactors versions.

**Comment by erogenousbeef** [comment]
Probably not going to do this. I've got big-reactors.com nicely automated, and I honestly CBA (a) checking to see if CurseForge has a compatible API and (b) integrating with it.

**Comment by octarine-noise** [comment]
It's actually pretty easy to automate. ForgeGradle has a built-in task for uploading artifacts to Curse.

see: https://github.com/MinecraftForge/ForgeGradle/wiki/CurseForge-Publishing

**Comment by RAnders00** [comment]
@erogenousbeef Would you mind opening this again because something new was offered by @octarine-noise?

**Comment by erogenousbeef** [comment]
I'll take a look, at least.

**Comment by hvdklauw** [comment]
Any progress?
Would really like to add Big Reactor to my own private profile
