### ISSUE TITLE
Block Type?

### ISSUE THREAD

**Issue by iDrewt** [erogenousbeef/BigReactors#474]
I was building a bunch of Reactors and Turbines and wanted to speed up the process by copying a blueprint and re-building via a Buildcraft builder... But it doesn't recognize any of the turbine blocks? I tried it in and out of the completed multi-block but it wouldnt let me copy it.. It would be awesome if these two mods would work better together! I was so excited when Carpenter Blocks worked with the builder, kinda bummed Big Reactor blocks wouldn't... I don't know if this is you or BC but thought I'd mention it :D

**Comment by erogenousbeef** [comment]
There's no special bits in BR recipes, so this would be a Buildcraft problem.

**Comment by Frontrider** [comment]
report it to buildcraft, and refer to tile entity handling.
