### ISSUE TITLE
FluidContainer registry/implementation issue

### ISSUE THREAD

**Issue by TheRoBrit** [erogenousbeef/BigReactors#475]
It would appear that the fluid containers (like buckets) do not appear to work as intended. Upon attempting to pick up Yellorium (or other fluids registered by the mod) it will revert the "Bucket" into a "Water Bucket". 

Replicable on version 0.4.3A.

**Comment by erogenousbeef** [comment]
The BR fluids are placeholders and aren't intended for actual use. Bugs regarding them will not be fixed in 0.4.

**Comment by ReikaKalseki** [comment]
When you get around to it, could you at least pick more realistic viscosity/density settings? Currently their (apparently) extreme ratio of high-density and low-viscosity is screwing up my fluid handling.
