### ISSUE TITLE
Crash on Forge 10.13.3.1373

### ISSUE THREAD

**Issue by louisw22** [erogenousbeef/BigReactors#477]
Crash Report: http://openeye.openmods.info/crashes/de80e73e53b93041d1ee91b9608cdd6d

I have tracked this crash down to be Big Reactors

**Comment by erogenousbeef** [comment]
I see no evidence for that assertion. Please explain, and provide reproduction steps.

**Comment by louisw22** [comment]
sure

**Comment by louisw22** [comment]
Well when I load the world It seems to crash when Advanced Genetics, Big reactors and Modular power suits enabled. So when I disable Advanced genetics it also crashes, or if i disable big reactors or Modular power suits on their own then it still crashes. However if i disable all three it does not crash on world creation.

**Comment by louisw22** [comment]
Any help?

**Comment by louisw22** [comment]
All mods are the most update to date as possible

**Comment by erogenousbeef** [comment]
It looks like you've got some corrupted data somewhere in your world, though precisely how it got there, I can't say. Enabling/disabling mods is likely just shifting around some IDs, and doesn't indicate that any particular mod is "at fault".

A quick Google search revealed several other similar stacktraces, [some](http://pastebin.com/T4c92Wmw) not including Big Reactors at all.

Easiest fix? Wipe your world.

**Comment by louisw22** [comment]
@erogenousbeef  It's nothing to do with world corruption, it always happens on new world creation or if an existing world is loaded

**Comment by erogenousbeef** [comment]
> A quick Google search revealed several other similar stacktraces, some not including Big Reactors at all.

I suggest continuing your search.

**Comment by octarine-noise** [comment]
There was a major change to FluidStacks in [Forge 1355](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1355-1.7.10/forge-1.7.10-10.13.3.1355-1.7.10-changelog.txt). This might be related. I've recently seen even weirder stacktraces with Fluid involvement while assembling a modpack.

@louisw22 : try downgrading to Forge 1352, and see if the problem goes away. That would confirm it.

**Comment by louisw22** [comment]
Yeah it does work on previous forge versions like 52 however the latest update to thermal expansion and other mods now require 55 and above, so I cannot revert
