### ISSUE TITLE
crash when 

### ISSUE THREAD

**Issue by flamin9001** [erogenousbeef/BigReactors#482]
i crash everytime i build a reactor on big reactors mod here is the crash report 
http://paste.ubuntu.com/10881964/

**Comment by flamin9001** [comment]
no i just get in and sit there for about 30 seconds and then crash

**Comment by flamin9001** [comment]
java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded! it is saying that

**Comment by flamin9001** [comment]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/24/15 5:07 PM
Description: Unexpected error

java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:230)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
	at Config.getWorldServer(Config.java:1741)
	at RandomMobs.entityLoaded(RandomMobs.java:49)
	at net.minecraft.client.renderer.RenderGlobal.func_72703_a(RenderGlobal.java:2878)
	at net.minecraft.world.World.func_72923_a(World.java:1347)
	at net.minecraft.client.multiplayer.WorldClient.func_72923_a(WorldClient.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1338)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.multiplayer.WorldClient.func_73027_a(WorldClient.java:226)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:765)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:230)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
	at Config.getWorldServer(Config.java:1741)
	at RandomMobs.entityLoaded(RandomMobs.java:49)
	at net.minecraft.client.renderer.RenderGlobal.func_72703_a(RenderGlobal.java:2878)
	at net.minecraft.world.World.func_72923_a(World.java:1347)
	at net.minecraft.client.multiplayer.WorldClient.func_72923_a(WorldClient.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1338)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.multiplayer.WorldClient.func_73027_a(WorldClient.java:226)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:765)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Flamin9001'/302, l='MpServer', x=521.81, y=59.82, z=559.30]]
	Chunk stats: MultiplayerChunkCache: 9, 14
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-11,64,223), Chunk: (at 5,4,15 in -1,13; contains blocks -16,0,208 to -1,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1917977 game time, 739843 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 29 total; [EntityTFNagaSegment['unknown'/832, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1088, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/833, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1089, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/834, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1090, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/835, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1091, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/836, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1092, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/837, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1093, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTrail['unknown'/518, l='MpServer', x=8.50, y=66.62, z=8.50], EntityTFNagaSegment['unknown'/838, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/839, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/840, l='MpServer', x=0.00, y=0.00, z=0.00], EntityClientPlayerMP['Flamin9001'/302, l='MpServer', x=521.81, y=59.82, z=559.30], EntityMinecartChest['entity.MinecartChest.name'/304, l='MpServer', x=512.50, y=16.34, z=550.78], EntitySkeletonCat['Skeleton Cat'/305, l='MpServer', x=526.38, y=64.00, z=547.31], EntityHat['unknown'/306, l='MpServer', x=8.50, y=66.62, z=8.50], EntityTFNagaSegment['unknown'/1082, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1083, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1084, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/829, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1085, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/830, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1086, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/831, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/1087, l='MpServer', x=0.00, y=0.00, z=0.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 298086008 bytes (284 MB) / 750067712 bytes (715 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B4 47 mods loaded, 47 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	OpenModsCore{0.7} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.1} [CoFH Core] (CoFHCore-[1.7.10]3.0.1-254.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BigReactors{0.4.2A2} [Big Reactors] (BigReactors-0.4.2A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Waila{1.5.3} [Waila] (Waila-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Baubles{1.0.1.8} [Baubles] (Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Thaumcraft{4.2.1.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	B0bGrowsOre{2.2.0} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.2.0 for 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Backpack{2.0.0} [Backpack] (Backpacks-Mod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod] (Balkons-Weapon-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	emeraldobsidianmod{1.3} [Emerald & Obsidian tools/armor mod] (Emerald-and-Obsidian-Tools-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	EnderIO{2.0_beta} [Ender IO] (enderio-2.0_beta.dev_mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ExWeapons{1.7} [ExWeapons Mod] (ExWeapons-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	foxlib{0.4.0} [FoxLib] (FoxLib-1.7.10-0.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	GraveStone{2.9.0} [GraveStone] (Gravestone-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	iChunUtil{4.0.0} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Hats{4.0.0} [Hats] (Hats-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	malisiscore{1.7.10-0.11.4} [MalisisCore] (malisiscore-1.7.10-0.11.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	malisisdoors{1.7.10-1.6} [Malisis' Doors] (malisisdoors-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	MoarFood{V5.8.0} [MoarFood] (MoarFood-5.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	MoreBows2{Beta 0.4} [More Bows 2] (More-Bows-2-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	OpenMods{0.7} [OpenMods] (OpenModsLib-1.7.10-0.7-snapshot-340 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	OpenBlocks{1.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4-snapshot-593.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Tails{$version} [Tails] (Tails-1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	telepads{1.6.4 v5} [Teleportation Pads] (TelePads-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	CoFHCore: -[1.7.10]3.0.1-254
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Frontrider** [comment]
EntityTFNagaSegment

Test it whitout twighlight forest.

**Comment by flamin9001** [comment]
I did and nothing still the same thing

**Comment by flamin9001** [comment]
now it let me get on for longer and this happened http://paste.ubuntu.com/10886789/

**Comment by erogenousbeef** [comment]
`tconstruct.blocks.slime.SlimeTallGrass` is at the top of the callstack. Report this is Tinker's Construct.
