### ISSUE TITLE
Reactor coolant ports and turbine fluid ports don't change modes.

### ISSUE THREAD

**Issue by mrsnowfoxy** [erogenousbeef/BigReactors#483]
Hello, I was having some issues in my single player world where once I added a reactor coolant port, While the interface did function and change, I am not able to change the mode from inlet to outlet. This is the case with both right clicking with wrenches and an empty hand,
The same thing goes for the turbine version. Is there something I am doing wrong?

**Comment by erogenousbeef** [comment]
Versions: BR, CofHCore, Forge. Screenshots.

**Comment by mrsnowfoxy** [comment]
CoFHCore is version 3.0.2-262
 BR is 0.4.3A 
and Forge is latest.

**Comment by erogenousbeef** [comment]
Strange. I'm assuming you're using the CoFH Crescent Hammer (the blue wrench-thing)? Might be some odd incompatibility introduced in the latest CoFHCore, but I both doubt it and hope not.

Does it work with older versions of CoFHCore?

**Comment by mrsnowfoxy** [comment]
Works with the Cresent Hammer,  Must have used the wrong wrench, Still doesn't with the hand thing though.

**Comment by raziel420** [comment]
could it have to do with the change to fluid handling in the latest
versions of forge?

**Comment by erogenousbeef-zz** [comment]
Sounds like a wrench incompatibility problem. Open-hand direction switching was removed a few versions ago.

**Comment by CarlSmotricz** [comment]
Sorry to necro, but just for info: The ports can't be switched with any of: Yeta Wrench, Crescent Hammer, the wrench from Extra Utilities, the Nether Quartz wrench from AE, the Flux Infused Battle Wrench or the Mekanism Configurator in Wrench mode.

What does work is the Extreme Wrench (from Extreme Reactors, natch).
