### ISSUE TITLE
FTB infinity crash (I assume big reactors caused it)

### ISSUE THREAD

**Issue by killerjerick** [erogenousbeef/BigReactors#487]
Hi, I've been play ftb infinity with a friend for about a month and recently, after updating ftb infinity which updates bigreactors to 1.4.3A I've been getting random server crashes, crash log is here: http://pastebin.com/KK4NeKNx

Any help would be greatly appretiated! 
Thanks,
Killerjerick

**Comment by erogenousbeef-zz** [comment]
Same fundamental issue as #486, #484, #447, #442, #392. See #486 for an explanation and resolution, and please use the search function in the future.

**Comment by killerjerick** [comment]
My apoligies, I searched google and came up with nothing, thanks though

**Comment by killerjerick** [comment]
So I looked at the solution, it can't be it, all I did was update ftb infinity, nothing else, I can't find a config file to edit item ID's either, so I don't understand how that's the problem...

**Comment by erogenousbeef-zz** [comment]
Precisely how or why the block IDs changed, I don't know, but they did. Your world's probably horribly corrupt at this point. Googling around quickly, there appears to be no way for users to correct them in 1.7.

Three possible solutions:
- Wipe your world
- Remove BR from your modpack, load all chunks which contain BR blocks, then re-add BR to your modpack (this effectively wipes all BR blocks out of the world and resets them to air)
- Remove all BR blocks from your world with MCEdit

**Comment by killerjerick** [comment]
Okay thanks for the hasty reply, I'll attempt MCEdit, hopefully I remember where all the blocks are.
