### ISSUE TITLE
Visual Issue with Turbine Formation

### ISSUE THREAD

**Issue by JadesMeister** [erogenousbeef/BigReactors#494]
Hello there,
I am having an issue with a turbine.
Upon completion of the construction of the turbine. The appearance does not change (connected textures, etc...). You can still see all the individual blocks, and the rotor does not show its spin animation. 

Additionally, the RPM remains zero, while there is energy being generated. 

Turbine Prior to completion (note the glass missing): http://prntscr.com/74z6jm
Turbine Post Completion (same shot): http://prntscr.com/74z6xd
GUI To confirm that Turbine activity: http://prntscr.com/74z84h

Apologies if this is a repeat of an earlier issue that I failed to locate prior to posting.

Besides the visual issue, the turbine still functions as needed. Generating power, and taking in steam. There _might_ be an issue with liquid transfer of exhaust, however that is not relevant here.

BigReactors Version: 0.4.3A
Using Minecraft Forge: 10.13.3.1395
Using FML Version: 7.10.130.1395

**Comment by PlanetBeast** [comment]
This can be closed. The bug was a mismatch in client-server config files.

**Comment by JadesMeister** [comment]
Ah okay.
