### ISSUE TITLE
Turbine/reactor steam pumping problems

### ISSUE THREAD

**Issue by SpEaGs** [erogenousbeef/BigReactors#499]
I'm running FTB Infinity v1.5.1 for MC 1.7.10 which has Big Reactors v 0.4.3a on both my server and client, but for some reason my turbine isn't transfering any steam to the available fluid pipes... I've tried all of the Ender I/O fluid conduits as well as the Thermal Dynamics hardened fluiducts. The reactor I'm using to fuel the turbine with steam generates steam, however doesn't pump it into the pipes, nor does the turbine extract its waste water
![br ticketpic1](https://cloud.githubusercontent.com/assets/5341601/7898733/8f64cfae-06d7-11e5-8302-9b9973f1fdd1.png)
![br ticketpic2](https://cloud.githubusercontent.com/assets/5341601/7898734/93cc171e-06d7-11e5-93a1-09e36031ffad.png)
![br ticketpic3](https://cloud.githubusercontent.com/assets/5341601/7898735/966fb052-06d7-11e5-9b86-26382723ca91.png)
 I was able to get the Turbine spinning with a creative steam generator, but that just circumvents the issue... If there's anything else i need to post to help solve this, just say the word and i'll do it. Thanks in advance!

EDIT: It seems that there's supposed to be a GUI for the fluid ports on the reactor and turbine, however right-clicking the ports does not bring up a GUI

**Comment by bookerthegeek** [comment]
You have both you fluid ports on the reactor set to input water. Neither is set to output steam.

Change the one one the right in the second picture so the arrows point out.

**Comment by SpEaGs** [comment]
how? there's no GUI for them...

**Comment by bookerthegeek** [comment]
Either it was right clicking with a wrench or an empty hand. Maybe a shift was required.

**Comment by SpEaGs** [comment]
neither way is working... maybe that's my issue then...

**Comment by bookerthegeek** [comment]
If I remember, and I might not be, the reactor had to be unformed for then to be able to swap the in/out arrows

**Comment by SpEaGs** [comment]
ok i'll see if that works

**Comment by SpEaGs** [comment]
breaking the multiblock did not fix it, but i tried the Forestry wrench and it worked with a simple right-click... thnx for the help!

**Comment by Frontrider** [comment]
You need a bc compatible wrench, ic2, or some screwdrivers woN't work.

**Comment by NattyC0** [comment]
Something like this is happening for me. my reactor is full of steam but when I go into my turbine sometimes the steam flashes a bit but then its empty again. When I turn the MB/t down I start to see the steam build up but when I put it higher its empty again even though my reactor is full of steam. WHYYYY?!!!?
