### ISSUE TITLE
Severe crash when adjusting turbine max input, computer bsods upon startup

### ISSUE THREAD

**Issue by professorial** [erogenousbeef/BigReactors#528]
I feel bad submitting such a severe report, in case it's not big reactor's fault, but it was what I was doing at the time of the crash,  so I can't think of anything else. 

I was playing FTB infinity, and was in my turbine's gui, adjusting the max fluid(steam) input. I clicked/shift clicked 'down', setting the value to 1889; then clicked 'up'; immediately, the screen filled with purple squares for a second or two, then went black and resonded to no inputs, including ctrl-alt-del. 

Attempting to reboot in normal mode immediately bluescreens my computer, while safe mode loads with graphical glitches (horizontal white lines). I tried reinstalling my graphics drivers with no success. I'm not sure what else to do.

No crash report seems to have been generated; though I do have the regular log, but since that would be a pain to try to upload from my phone and I didn't see any irregularities (just calls to big reactor's gui stuff), I won't be doing that right now. 

It's probably worth noting my turbine had two separate fluid import blocks, each connected to a different pipe network (a reactor and two railcraft boilers)

I'm running windows 7 64bit.

**Comment by RogueLogix** [comment]
what graphics card do you have?

**Comment by professorial** [comment]
GTX 570, sorry, thought I said. I ended up replacing it entirely. While I still don't know if I could've fixed the problem or not, I happened to have a spare lying around, so replacing it was the easiest thing to do.

**Comment by RogueLogix** [comment]
do you still have the problem?
if not that was the problem.
that is common to happen when a gpu overheats for to long. it could just be a coincidence that it happened when you clicked that but it could of caused a gpu spike and killed it.

**Comment by professorial** [comment]
no, it's clear now. I'm thinking that's probably the most likely scenario, considering some of its prior performance (and my bad habit of leaving things running). The timing of the crash was just so impeccable that I didn't consider a simpler scenario.

**Comment by RogueLogix** [comment]
yeah it happens.

**Comment by professorial** [comment]
Yeah, I'm just glad I had a spare. Closing this issue then I guess.
