### ISSUE TITLE
Game crashes when rednet is placed down

### ISSUE THREAD

**Issue by ghost** [erogenousbeef/BigReactors#533]
So whenever i have a full working reactor and i add a rednet controller block to the multiblock my game crashes and im just trying to get like a computercraft program to work can someone please help me.

**Comment by sameer** [comment]
Do you have the crash log?

**Comment by ghost** [comment]
Im sorry but i had this problem along time ago and since haven't used the mod for awhile since mabey september so im sorry for the inconvience and have a good day
