### ISSUE TITLE
240mb cap active cooled reactor

### ISSUE THREAD

**Issue by Fabboz** [erogenousbeef/BigReactors#538]
HI,

Initially my reactor produce 9600 mb/tick of steam before connecting it to a turbine it drop to 240 mb/tick.
I had the same problem on others reactors with different size, type, material etc anyway to 240 mb/tick.

I think that the problem is not in connecting to a turbine due to the many try i done, modifing the size to the sky don't increase the steam produced etc.
Sorry but i don't have the photo of the last reactor but is so big like 10_10_3 with a lot of control rod and crioteum cooled (all made in creative mode).
I run the last version of the mode and the last cofh core.

Greetings for the nice mod.

waiting a reply

thx bye

**Comment by bookerthegeek** [comment]
No idea without pictures, BUT I know that as soon you actually start using the "coolant" (water) to power the turbine it lowers the internal temp of the reactor, thereby reducing the amount of coolant you produce.
