### ISSUE TITLE
My Modpack crashes when using Big Reactors

### ISSUE THREAD

**Issue by Luysita** [erogenousbeef/BigReactors#546]
Hello, I added Big Reactors to my personal modpack today and it crashes when using Thaumcraft mob aspects. I am using MultiMC launcher and forge 1517.
I disabled Thaumcraft mob aspects from the mod list and now worked fine, but I really want to use both mods.
Is there a fix? Thank you.

http://pastebin.com/cew3fSpb

Big reactors version: BigReactors-0.4.3A
Thaumcraft mob aspects version: ThaumcraftMobAspects-1.7.2-2A

**Comment by LokeYourC3PH** [comment]
Analyzing the crash log, i dont see Big Reactors anywhere else other than in the successfully loaded mods list. You might want to report this to the Thaumcraft Mob Aspects mod maker, as BigReactors is not at fault here.

**Comment by Luysita** [comment]
It has been solved.
