### ISSUE TITLE
Crash with Latest Version

### ISSUE THREAD

**Issue by Swordsyke** [erogenousbeef/BigReactors#558]
Someone on my server crashed the server, and we're using version 0.4.3A, the latest version. The crash log looks highly similar to one where a person used a TConstruct hammer on a BigReactor, as referenced below: 
My Pastebin: http://pastebin.com/amvTgiVJ
Referenced Pastebin: http://pastebin.com/wGnNXyYx

Please help me resolve this issue to increase the stability of my server and help others having issues. Thank you very much ahead of time for your insight.

**Comment by sameer** [comment]
@Swordsyke Do not recreate issues that have already been solved. Read my pull request (https://github.com/erogenousbeef/BigReactors/pull/551). If you do not know how to compile this let me know and I'll put something together for you.

**Comment by sameer** [comment]
@Swordsyke remove your log right away. You have posted the coordinates of your players in it (ctrl +f "entityplayer").

**Comment by XFactHD** [comment]
The crash report is the same. Seems that someone did click the controller with a tcon tool. This crash should not have any impact on the server as long as nobody clicks a controller with a tcon tool again.
As a side note: This mod seems to be dead meaning that you won't get any fix for that.

**Comment by Swordsyke** [comment]
Log deleted to remove player coordinates. @Robotia I do not know how to edit the java class file, could you do that for me and possibly shoot me a dropbox link or something with it when you're done? I would really appreciate it! Thank you!

**Comment by Swordsyke** [comment]
*A dropbox link with the mod file once the class file inside of it has been edited.

**Comment by sameer** [comment]
@XFactHD Did you even read what I said? I have already resolved the issue in the pull request I mentioned.

@Swordsyke Sure thing.

**Comment by sameer** [comment]
@Swordsyke Compiled jar posted at https://accretion.us/development. Direct download jar [here](https://accretion.us/repo/development/mods/BR_robotia_class_cast_jan19.jar).

**This issue should now be closed.**

**Comment by Swordsyke** [comment]
Thank you very much! I'll post again here if it messes up again somehow. I appreciate the work, and I'd love it if you checked out this issue also: https://github.com/Chicken-Bones/CodeChickenLib/issues/33
It's causing several issues on my server.

**Comment by sameer** [comment]
@Swordsyke `CodeChickenLib-1.7.10-1.1.3.136-universal.jar` 
Are you using this version? If not, I'll send that to you, it's the one that works on my Tekkit Legends server.

**Comment by Swordsyke** [comment]
CodeChickenLib-1.7.10-1.1.3.138-universal.jar is the version that I am using. Due to it being a coremod, if I change the version from 138 to 136, would players still be able to login if their clients had version 138?

**Comment by XFactHD** [comment]
@Robotia when I wrote that answer, you hadn't written yours. I didn't refresh the page before posting.

**Comment by sameer** [comment]
@XFactHD Ah, ok. All good :)

**Comment by Swordsyke** [comment]
Can you please answer my question Robotia?

**Comment by sameer** [comment]
@Swordsyke try it on a test server, I haven't messed with CodeChicken before.
