### ISSUE TITLE
[0.4.3A] Reactors forming and unforming, turning off, between player Relogs

### ISSUE THREAD

**Issue by callous4567** [erogenousbeef/BigReactors#563]
**Hello!**
So i'm not one for Github issues, but this one is a pretty important one for me to report. I don't know if anyone else has had this issue, and i've checked the other issues but can't find someone who has.

**What's the issue?**
Every time I relog, the reactor goes out of it's formation. So, it will no longer be a multiblock.
To replicate this, just set up an RR server with a few people, make your reactor 80_80_80, alter the configs to allow these reactors (size wise, etcetera), then pass out the configs to the server folks. It just doesn't work for some reason.

I gave out configs on part of Emberquill, which did infact make it work in the first place, but now that we all have the configs, it still isn't working. 

**Logs or whatever kind of stuff you might need?**
https://drive.google.com/file/d/0BxDhqkUPGOFCWVBZU1F0M2NVY00/view?usp=sharing

**Comment by sameer** [comment]
It might be the fact that the reactor is built on overlapping chunks 0.o

**Comment by callous4567** [comment]
So I can't put a reactor on overlapping chunks...?

**Comment by callous4567** [comment]
I have them all chunk loaded (if that is the case of it causing issues)

**Comment by sameer** [comment]
No, I am just saying the fact that is on overlapping chunks could influence your setup. That's covering at least 5x5 chunks.

**Comment by callous4567** [comment]
Yep, it's covering about 7x7 chunks in total (it overlaps); I have a dim. anchor for an area of 13x13 chunks (around its centre), so it shouldn't be an issue?

**Comment by bookerthegeek** [comment]
What are you using to chunkload?

**Comment by callous4567** [comment]
Dim. Anchor, it's all we have, and it works fine/worked fine.

**Comment by callous4567** [comment]
https://www.youtube.com/watch?v=jaS-_DxLKgA&feature=youtu.be

In general it'll return to its normal state after a few seconds, but that's the issue pretty much.

**Comment by bookerthegeek** [comment]
Does this happen with smaller reactors?

Off the top of my head I can only assume that it is taking a while to form due to size.

**Comment by callous4567** [comment]
Smaller reactors work fine; only this one fails. It doesn't run if no one is near it, and if it isn't loaded, etcetera, and the items disappear upon reforming; at the least they did for me once so far when I lost 100% of it's filling, which is a lot :_:

**Comment by callous4567** [comment]
Appears to be working, sort of. I can settle with it for now, closing the issue.
