### ISSUE TITLE
Glitch with always 100 % Fuel

### ISSUE THREAD

**Issue by BlazingGamer** [erogenousbeef/BigReactors#564]
![2016-02-15_23 17 50](https://cloud.githubusercontent.com/assets/13196222/13082208/cdd1871e-d4e0-11e5-8180-19b72835228f.png)

**Comment by Tomson124** [comment]
Could you please provide some more information? What did you do in order to get this "glitch"?
Maybe even the log file?

**Comment by BlazingGamer** [comment]
Oh, sorry that is my fault, didn't understand the meaning of "100 % Full" at first... LOL
