### ISSUE TITLE
I keep crashing.

### ISSUE THREAD

**Issue by carlwfoster** [erogenousbeef/BigReactors#571]
After I turn on my particle accelerator, a few seconds later I crash. I do not know why but I do have 3 turbines 15 x 15 x 13 with 2 reactors one is 32 x 8 x 13 and the other one is 17 x 8 x 13. the particle accelerator is 80 x 110. I am trying to make dark matter.

This is the crash report: [crash-2016-04-03_12.49.04-server.txt](https://github.com/erogenousbeef/BigReactors/files/201475/crash-2016-04-03_12.49.04-server.txt)

These are the screen shots if you need them: 
![2016-04-03_13 02 02](https://cloud.githubusercontent.com/assets/18248418/14233946/6aa21268-f99c-11e5-8336-7858f8cb4040.png)
![2016-04-03_13 01 55](https://cloud.githubusercontent.com/assets/18248418/14233949/702af114-f99c-11e5-9650-931b8c5821db.png)
![2016-04-03_13 01 43](https://cloud.githubusercontent.com/assets/18248418/14233952/72da5dbe-
![2016-04-03_13 01 25](https://cloud.githubusercontent.com/assets/18248418/14233961/8e4c75f0-f99c-11e5-88d5-7205117676b8.png)

**Comment by sameer** [comment]
The crash is caused by chicken chunk loaders, not big reactors.

**Comment by carlwfoster** [comment]
So i should remove all chicken chunk loaders in my world?

**Comment by carlwfoster** [comment]
I just removed all of them and i am not crashing thanks!!

**Comment by carlwfoster** [comment]
nvm just crashed let me get crash report

**Comment by carlwfoster** [comment]
[crash-2016-04-03_13.41.24-server.txt](https://github.com/erogenousbeef/BigReactors/files/201498/crash-2016-04-03_13.41.24-server.txt)

**Comment by Fayti1703** [comment]
"at codechicken.chunkloader.PlayerChunkViewerManager.update
at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd"
Not sure if you still have some chunkloaders or if it's just code that always runs. 
Either way, it appears to be chickenchunks' fault.

**Comment by AngryCarrot789** [comment]
ik im 4 years late but this is a problem with the single player server, and even if you move to multiplayer, like cauldron even if you host it locally, the particle accelerator will crash your game because that has a bug too
