### ISSUE TITLE
Thermal Expansion Issue 

### ISSUE THREAD

**Issue by ProtoGamer** [erogenousbeef/BigReactors#591]
I was playing in my world, when i closed them and 20min later i restarted it but when I'm entering in the world the game crashes and i don't  know how can i recover the world. 

Log: http://pastebin.com/sXiqE2Bb
Please help me !

**Comment by XFactHD** [comment]
I have no idea how you came to the conclusion that this crash is caused by BR and TE. If you read the first lines of the crash report you can clearly see that this is caused by BetterFurnaces and Traincraft.

**Comment by ProtoGamer** [comment]
Thanks but I resolve it 20 min later ahahhah
