### ISSUE TITLE
Unable to shift click Coal into the fuel slot in a furnace.

### ISSUE THREAD

**Issue by dro800** [erogenousbeef/BigReactors#592]
Whenever I attempt to shift click Coal into the furnace, it places it in the top slot instead of the fuel slot. The reason I believe this to be a Big Reactors issue is because the mod adds Graphite Ingots which are made by putting coal into a furnace. Running Big Reactors 0.4.3A with Forge 1.7.10 - 10.13.4.1614. Thanks in advance and I hope to get a response soon.

**Comment by XFactHD** [comment]
This not a bug. The vanilla furnace prefers the ingredient slot over the fuel slot when shift clicking and because you smelt coal to make graphite, coal will go into the ingredient slot when shift clicked. Nothing that could be done about this.

**Comment by dro800** [comment]
@XFactHD Oh alright, I see. Thanks for replying.
